server:
  port: 8080

spring:
  application:
    name: user-service
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/user_db}

app:
  jwt:
    secret: "boost-is-the-secret-of-my-energy-boost-is-the-secret-of-my-energy"
    expiration-ms: 86400000 # 24 hours