spring:
  application:
    name: user-service
  mongodb:
    uri: ${USER_MONGO_URI:mongodb://user-db:27017/user_db}

server:
  port: 3000
  address: 0.0.0.0

app:
  jwt:
    secret: "boost-is-the-secret-of-my-energy-boost-is-the-secret-of-my-energy"
    expiration-ms: 86400000 # 24 hours